[package]
name = "ark-probe-ebpf-ebpf"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
aya-bpf = { version = "0.12", features = ["core"] }
aya-log-ebpf = "0.2"

[profile.release]
strip = true
lto = true
